# Generated by Django 4.0.4 on 2022-05-11 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_followerscount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='following',
            new_name='user',
        ),
    ]
